"""Fix fk ondelete

Revision ID: e5c2ce8c0cda
Revises: 0fc72cf8bbf3
Create Date: 2026-05-08 19:45:30.552737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c2ce8c0cda'
down_revision: Union[str, None] = '0fc72cf8bbf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trusted_contacts_user_id_fkey', 'trusted_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'trusted_contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trusted_contacts', type_='foreignkey')
    op.create_foreign_key('trusted_contacts_user_id_fkey', 'trusted_contacts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
